######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 19:03:13 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += console.hpp
SOURCES += console.cpp main.cpp
